version: '3'
services:
  db:
    build: ./db
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: db_projeto_final
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password12